### ISSUE TITLE
Exception during iam-get-credential-report check

### ISSUE THREAD

**Issue by arkadiyt** [duo-labs/cloudmapper#127]
Hi,

I'm getting the following exception when running:
```
python cloudmapper.py collect --profile core --account core
```
```
Making call for account-data/./core/us-east-1/iam-get-credential-report.json
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.amazonaws.com
Traceback (most recent call last):
  File "cloudmapper.py", line 69, in <module>
    main()
  File "cloudmapper.py", line 64, in main
    commands[command].run(arguments)
  File "/Users/arkadiy/appsec/cloudmapper/commands/collect.py", line 198, in run
    collect(args)
  File "/Users/arkadiy/appsec/cloudmapper/commands/collect.py", line 174, in collect
    call_function(filepath, handler, method_to_call, parameters)
  File "/Users/arkadiy/appsec/cloudmapper/commands/collect.py", line 84, in call_function
    f.write(json.dumps(data, indent=4, sort_keys=True, default=datetime_handler))
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/Users/arkadiy/appsec/cloudmapper/shared/common.py", line 70, in datetime_handler
    raise TypeError("Unknown type")
TypeError: Unknown type
```

**Comment by mtpettyp** [comment]
Looks like the response to `get_credential_report` is returning a `Content` key that contains a byte literal value.

**Comment by 0xdabbad00** [comment]
Thank you @mtpettyp for looking into this and providing a fix.
