### ISSUE TITLE
Exception in expaccount in <all regions> when running audit

### ISSUE THREAD

**Issue by alanmcg** [duo-labs/cloudmapper#216]
> python cloudmapper.py audit --config devconfig.json --account expaccount
Finding resources in account expaccount (<hidden>)
Exception in expaccount in ap-south-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in eu-west-3
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in eu-west-2
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in eu-west-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in ap-northeast-2
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in ap-northeast-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in sa-east-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in ca-central-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in ap-southeast-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in ap-southeast-2
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in eu-central-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in us-east-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 532, in audit
    audit_cloudtrail(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 50, in audit_cloudtrail
    if len(json_blob['trailList']) == 0:
KeyError: 'trailList'
Exception in expaccount in us-east-2
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in us-west-1
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'
Exception in expaccount in us-west-2
Traceback (most recent call last):
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 538, in audit
    audit_ebs_snapshots(region)
  File "/home/alamcg/dev/git/cloudmapper/commands/audit.py", line 200, in audit_ebs_snapshots
    for snapshot in json_blob['Snapshots']:
KeyError: 'Snapshots'

**Comment by 0xdabbad00** [comment]
Hmm, maybe when you ran the `collect` command you didn't have privileges to get information about ebs snapshots, so it didn't download that data correctly?

**Comment by 0xdabbad00** [comment]
Closing due to staleness
