### ISSUE TITLE
Prepare data error KeyError: 'cidrs'

### ISSUE THREAD

**Issue by gnasr** [duo-labs/cloudmapper#28]
Hi, i just caught this error when i tried to prepare data, i'm running on MacOS Sierra and Python 2.7.10
```
python cloudmapper.py prepare --account Dev
Building data for account Dev (0000123456)
- 0 nodes built in region ap-south-1
- 0 nodes built in region eu-west-3
- 0 nodes built in region eu-west-2
- 0 nodes built in region eu-west-1
- 0 nodes built in region ap-northeast-2
- 0 nodes built in region ap-northeast-1
- 0 nodes built in region sa-east-1
- 0 nodes built in region ca-central-1
- 0 nodes built in region ap-southeast-1
- 0 nodes built in region ap-southeast-2
- 0 nodes built in region eu-central-1
- 90 nodes built in region us-east-1
- 0 nodes built in region us-east-2
- 0 nodes built in region us-west-1
- 0 nodes built in region us-west-2
Traceback (most recent call last):
  File "cloudmapper.py", line 121, in <module>
    main()
  File "cloudmapper.py", line 111, in main
    run_prepare(arguments)
  File "cloudmapper.py", line 90, in run_prepare
    prepare(account, config, outputfilter)
  File "/private/tmp/cloudmapper/cloudmapper/prepare.py", line 339, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/private/tmp/cloudmapper/cloudmapper/prepare.py", line 292, in build_data_structure
    for cidr in get_external_cidrs(account, config):
  File "/private/tmp/cloudmapper/cloudmapper/prepare.py", line 120, in get_external_cidrs
    external_cidrs.append(Cidr(cidr, get_cidr_name(cidr, config)))
  File "/private/tmp/cloudmapper/cloudmapper/prepare.py", line 125, in get_cidr_name
    return config["cidrs"].get(cidr, {}).get("name", None)
KeyError: 'cidrs'
```

**Comment by 0xdabbad00** [comment]
Can you check your `config.json` looks similar to https://github.com/duo-labs/cloudmapper/blob/master/config.json.demo ?  Even if you don't specify any cidrs you should have `"cidrs": {}`.

I'll make a code change to check for this.
