### ISSUE TITLE
pyjq reports "Cannot iterate over null"

### ISSUE THREAD

**Issue by zaro0508** [duo-labs/cloudmapper#309]
$ python ./cloudmapper.py prepare --config config.json.arch --account arch
Building data for account arch (XXXXXXXXX)
Traceback (most recent call last):
  File "./cloudmapper.py", line 70, in <module>
    main()
  File "./cloudmapper.py", line 65, in main
    commands[command].run(arguments)
  File "/home/ec2-user/cloudmapper/commands/prepare.py", line 419, in run
    prepare(account, config, outputfilter)
  File "/home/ec2-user/cloudmapper/commands/prepare.py", line 345, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/home/ec2-user/cloudmapper/commands/prepare.py", line 215, in build_data_structure
    for region_json in get_regions(account, outputfilter):
  File "/home/ec2-user/cloudmapper/shared/common.py", line 132, in get_regions
    regions = pyjq.all('.Regions[]{}'.format(region_filter), region_data)
  File "/home/ec2-user/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)

My Enviroment:

$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

$ python -V
Python 3.6.8

$ pip freeze
boto3==1.9.104
botocore==1.12.104
colorama==0.3.9
docutils==0.14
jmespath==0.9.4
netaddr==0.7.19
numpy==1.16.2
policyuniverse==1.2.0.1
pyasn1==0.4.5
pyjq==2.3.1
python-dateutil==2.8.0
PyYAML==3.13
rsa==3.4.2
s3transfer==0.2.0
six==1.12.0
urllib3==1.24.1

**Comment by 0xdabbad00** [comment]
As this threw an exception when parsing the region info, I suspect that there has some issue with collecting the data or that the collected data has been modified.  Please check the contents of the file `./account-data/arch/describe-regions.json`
