### ISSUE TITLE
UI Crashes during load - BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by amitcohen5** [duo-labs/cloudmapper#314]
I'm using MAC High Sierra 10.13.6

`Exception happened during processing of request from ('127.0.0.1', 54855)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 639, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 800, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe`

Python version  : 3.6.5

My Environment : 
boto3==1.9.107
botocore==1.12.107
docutils==0.14
Jinja2==2.10
jmespath==0.9.4
MarkupSafe==1.1.1
netaddr==0.7.19
numpy==1.16.2
policyuniverse==1.2.0.1
pyjq==2.3.1
python-dateutil==2.8.0
PyYAML==3.13
s3transfer==0.2.0
six==1.12.0
urllib3==1.24.1

**Comment by 0xdabbad00** [comment]
What command did you run?  I'm guessing `python cloudmapper.py webserver`?

Try running `python -m http.server` which does almost entirely the same thing.  I suspect the issue is not CloudMapper, but something else going on your system.

**Comment by amitcohen5** [comment]
@0xdabbad00  
python -m web.server returns no output however, 
python -m SimpleHTTPServer works fine 

I forgot to mention that i am able to access the UI ,  it completes half of the loading and then crashes.

**Comment by 0xdabbad00** [comment]
Due to `SimpleHTTPServer` working, you are likely using python 2, as opposed to python 3, which means you are likely not working from within the `pipenv` shell.  I really think your environment must be broken.  All the `webserver` command does is run a simple web server, so you can work around this by just running `python -m http.server --bind 127.0.0.1` from within the `web` directory.

**Comment by amitcohen5** [comment]
@0xdabbad00  why do you assume such thing?  you can clearly see that the python code is loading from 3.6,  i've also uninstalled and installed python 3.7 and when i run python i get 3.7 shell within my env (pipenv shell) ,   the web server is starting ,  UI loading  and after some time crashes.
