### ISSUE TITLE
SyntaxError: invalid syntax common.py - common.py

### ISSUE THREAD

**Issue by shreevij** [duo-labs/cloudmapper#338]
I am getting a below syntex error either with demo or my account settings. 

$ sudo python cloudmapper.py prepare --config config.json.demo --account demo
Traceback (most recent call last):
  File "cloudmapper.py", line 70, in <module>
    main()
  File "cloudmapper.py", line 54, in main
    module = importlib.import_module(full_package_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vkumar/cloudmapper-master/commands/amis.py", line 10, in <module>
    from shared.common import parse_arguments, query_aws, make_list, get_regions
  File "/home/vkumar/cloudmapper-master/shared/common.py", line 240
    for principal_auth in [*json_account_auth_details['UserDetailList'], *json_account_auth_details['RoleDetailList']]:
                           ^
SyntaxError: invalid syntax
$

**Comment by 0xdabbad00** [comment]
My guess is you might not be running in the `pipenv shell` which would force use of Python 3.

**Comment by shreevij** [comment]
Thanks for the quick solution.
