### ISSUE TITLE
_pyjq.ScriptRuntimeError: Cannot iterate over null (null) - Prepare Module

### ISSUE THREAD

**Issue by rams3sh** [duo-labs/cloudmapper#340]
I get the following error when I run prepare modue in my dataset.
```
Traceback (most recent call last):
  File "cloudmapper.py", line 70, in <module>
    main()
  File "cloudmapper.py", line 65, in main
    commands[command].run(arguments)
  File "/home/osboxes/Downloads/cloudmapper/commands/prepare.py", line 419, in run
    prepare(account, config, outputfilter)
  File "/home/osboxes/Downloads/cloudmapper/commands/prepare.py", line 345, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/home/osboxes/Downloads/cloudmapper/commands/prepare.py", line 306, in build_data_structure
    for c, reasons in get_connections(cidrs, vpc, outputfilter).items():
  File "/home/osboxes/Downloads/cloudmapper/commands/prepare.py", line 145, in get_connections
    for sg in instance.security_groups():
  File "/home/osboxes/Downloads/cloudmapper/shared/nodes.py", line 321, in security_groups
    return pyjq.all('.SecurityGroups[]', self._json_blob)
  File "/usr/local/lib/python3.6/dist-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)
```

Based on my dataset , SecurityGroups is not present as key in all json blobs being received at nodes.py.

Changing the following line :- 
`return pyjq.all('.SecurityGroups[]', self._json_blob)`

to 

`return pyjq.all('.SecurityGroups[]?', self._json_blob)`

solved the issue.

**Comment by 0xdabbad00** [comment]
Thank you for identifying the problem and solution for this.  This has similarly been documented in #205, so I'm going to close this ticket and continue leaving that one open until I fix this in the code.
