### ISSUE TITLE
KeyError: 'GeneratedTime' in  report 

### ISSUE THREAD

**Issue by vkamlesh** [duo-labs/cloudmapper#410]
(cloudmapper) bash-3.2$  python cloudmapper.py report --account myaccount --accounts citrus --log_level ERROR --config config.json --max-age 300
Traceback (most recent call last):
  File "cloudmapper.py", line 73, in <module>
    main()
  File "cloudmapper.py", line 67, in main
    commands[command].run(arguments)
  File "/Users/kamlesh.verma/my_homeproject/aws/cloudmapper/commands/report.py", line 374, in run
    report(accounts, config, args)
  File "/Users/kamlesh.verma/my_homeproject/aws/cloudmapper/commands/report.py", line 55, in report
    'collection_date': get_collection_date(account)})
  File "/Users/kamlesh.verma/my_homeproject/aws/cloudmapper/shared/common.py", line 252, in get_collection_date
    return json_blob['GeneratedTime'][:10]
KeyError: 'GeneratedTime'

**Comment by frederiksf** [comment]
Same here

**Comment by 0xdabbad00** [comment]
Did you run the `collect` step?  Compare the file `account-data/demo/us-east-1/iam-get-credential-report.json` against the file that was collected for your account.  My guess is either that file does not exist, or possibly the credential report had not finished being generated by the time the call was made to collect it.  I don't have any error handling for that possibility.

**Comment by 0xdabbad00** [comment]
I now check for the existence of the credential report file in #460.  I believe (as mentioned above) that the problem stems from not having run the `collect` command previously, but that is not clear in the exception until now.
