### ISSUE TITLE
collect fails because of unkown service s3control

### ISSUE THREAD

**Issue by isbkch** [duo-labs/cloudmapper#421]
Running the command `python cloudmapper.py collect --account devAccount`
Gives me the output bellow

```
* Getting s3control:get-public-access-block info
Traceback (most recent call last):
  File "cloudmapper.py", line 73, in <module>
    main()
  File "cloudmapper.py", line 67, in main
    commands[command].run(arguments)
  File "/Users/username/Projects/cloudmapper/commands/collect.py", line 371, in run
    collect(args)
  File "/Users/username/Projects/cloudmapper/commands/collect.py", line 227, in collect
    handler = session.client(runner['Service'], region_name=region['RegionName'])
  File "/Users/username/.virtualenvs/cloudmapper-WkZRcN-E/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/session.py", line 885, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py", line 69, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py", line 102, in _load_service_model
    api_version=api_version)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/loaders.py", line 378, in load_service_model
    known_service_names=', '.join(sorted(known_services)))
botocore.exceptions.UnknownServiceError: Unknown service: 's3control'. Valid service names are: acm, acm-pca, alexaforbusiness, apigateway, application-autoscaling, appstream, appsync, athena, autoscaling, autoscaling-plans, batch, budgets, ce, cloud9, clouddirectory, cloudformation, cloudfront, cloudhsm, cloudhsmv2, cloudsearch, cloudsearchdomain, cloudtrail, cloudwatch, codebuild, codecommit, codedeploy, codepipeline, codestar, cognito-identity, cognito-idp, cognito-sync, comprehend, config, connect, cur, datapipeline, dax, devicefarm, directconnect, discovery, dlm, dms, ds, dynamodb, dynamodbstreams, ec2, ecr, ecs, efs, eks, elasticache, elasticbeanstalk, elastictranscoder, elb, elbv2, emr, es, events, firehose, fms, gamelift, glacier, glue, greengrass, guardduty, health, iam, importexport, inspector, iot, iot-data, iot-jobs-data, iot1click-devices, iot1click-projects, iotanalytics, kinesis, kinesis-video-archived-media, kinesis-video-media, kinesisanalytics, kinesisvideo, kms, lambda, lex-models, lex-runtime, lightsail, logs, machinelearning, macie, marketplace-entitlement, marketplacecommerceanalytics, mediaconvert, medialive, mediapackage, mediastore, mediastore-data, mediatailor, meteringmarketplace, mgh, mobile, mq, mturk, neptune, opsworks, opsworkscm, organizations, pi, pinpoint, polly, pricing, rds, redshift, rekognition, resource-groups, resourcegroupstaggingapi, route53, route53domains, s3, sagemaker, sagemaker-runtime, sdb, secretsmanager, serverlessrepo, servicecatalog, servicediscovery, ses, shield, sms, snowball, sns, sqs, ssm, stepfunctions, storagegateway, sts, support, swf, transcribe, translate, waf, waf-regional, workdocs, workmail, workspaces, xray
```

**Comment by 0xdabbad00** [comment]
I suspect you did not install CloudMapper properly, as this indicates to me that you are using an older version of `boto` that doesn't know about `s3control`, which means you didn't run:
```
pipenv install --skip-lock
pipenv shell
```

**Comment by isbkch** [comment]
I actually did, I followed the installation guide for MacOs exactly as its written.

```
$ pipenv install --skip-lock
Installing dependencies from Pipfile…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 11/11 — 00:00:03
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```
Then

```
$ pipenv shell
Launching subshell in virtual environment…
bash-3.2$  . /Users/username/.virtualenvs/cloudmapper-WkZRcN-E/bin/activate
```
Then

`(cloudmapper) bash-3.2$ python cloudmapper.py collect --account devAccount`

And that's where I get the issue

**Comment by 0xdabbad00** [comment]
Hmm, maybe you're running in a different partition?  Are you running in gov-cloud or China maybe?  CloudMapper support is minimal there as I don't have access to either of those partitions.

**Comment by isbkch** [comment]
Not at all, I'm running on us-east-1

Le sam. 25 mai 2019 12 h 03 p.m., Scott Piper <notifications@github.com> a
écrit :

**Comment by 0xdabbad00** [comment]
My best guess is still that somehow it's not using the expected boto3 library version.  Try this, from a `pipenv shell`, run `python`, `import boto3` and `print(boto3.__version__)`. That should print `1.9.145`. 

Your session should look like this:

```
$ pipenv shell
Launching subshell in virtual environment…
bash-3.2$  XXX/.local/share/virtualenvs/cloudmapper-rt_DstOG/bin/activate
(cloudmapper-rt_DstOG) bash-3.2$ python
Python 3.7.0 (default, Sep 18 2018, 18:47:22)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> print(boto3.__version__)
1.9.145
```

**Comment by isbkch** [comment]
Here is my output

```
~/Projects/cloudmapper => pipenv shell
Launching subshell in virtual environment…
bash-3.2$  . /Users/username/.virtualenvs/cloudmapper-WkZRcN-E/bin/activate
(cloudmapper) bash-3.2$ python
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> print(boto3.__version__)
1.9.145
>>>
```

The only way I was able to able to make this work is by commenting all `s3control` instances, otherwise, it still throws the error even though boto3 version seems to be correct

**Comment by 0xdabbad00** [comment]
Maybe the underlying `botocore` version is incorrect somehow?

You could try this, and this is the output I get.

```
$ python
Python 3.7.0 (default, Sep 18 2018, 18:47:22)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import botocore
>>> print(botocore.__version__)
```

**Comment by 0xdabbad00** [comment]
Closing due to staleness. I believe the original issue was still somehow due to `botocore` not being on the correct version.
