### ISSUE TITLE
KeyError: 'PublicIPAddress' during prepare command

### ISSUE THREAD

**Issue by Merenon** [duo-labs/cloudmapper#447]
I experienced the following KeyError exception during a "prepare" run:
```
$ python cloudmapper.py prepare --config [CONFIG] --account [ACCOUNT]
[...]
Traceback (most recent call last):
  File "cloudmapper.py", line 73, in <module>
    main()
  File "cloudmapper.py", line 67, in main
    commands[command].run(arguments)
  File "[PATH]/cloudmapper/commands/prepare.py", line 649, in run
    prepare(account, config, outputfilter)
  File "[PATH]/cloudmapper/commands/prepare.py", line 569, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "[PATH]/cloudmapper/commands/prepare.py", line 479, in build_data_structure
    for c, reasons in get_connections(cidrs, vpc, outputfilter).items():
  File "[PATH]/cloudmapper/commands/prepare.py", line 211, in get_connections
    for ip in sourceInstance.ips:
  File "[PATH]/cloudmapper/shared/nodes.py", line 685, in ips
    ips.append(cluster_node['PublicIPAddress'])
KeyError: 'PublicIPAddress'
```
I just added a try-except in the _shared/nodes.py_ file as workaround, which solved it for the moment:
```
@property
    def ips(self):
        ips = []
        for cluster_node in self._json_blob['ClusterNodes']:
            try:
                ips.append(cluster_node['PrivateIPAddress'])
                ips.append(cluster_node['PublicIPAddress'])
            except:
                continue
        return ips
```

EDIT:
It indeed seems to expect both private and public IPs to be assigned to Redshift cluster nodes:
```
$ cat account-data/[ACCOUNT]/eu-central-1/redshift-describe-clusters.json
{
    "Clusters": [
        {
            "AllowVersionUpgrade": true,
            "AutomatedSnapshotRetentionPeriod": 5,
            "AvailabilityZone": "eu-central-1b",
            "ClusterCreateTime": "2019-01-27T00:47:29.584000+00:00",
            "ClusterIdentifier": "CLUSTERNAME",
            "ClusterNodes": [
                {
                    "NodeRole": "LEADER",
                    "PrivateIPAddress": "10.0.0.1"
                },
                {
                    "NodeRole": "COMPUTE-0",
                    "PrivateIPAddress": "10.0.0.3"
                },
                {
                    "NodeRole": "COMPUTE-1",
                    "PrivateIPAddress": "10.0.0.2"
                },
                {
                    "NodeRole": "COMPUTE-2",
                    "PrivateIPAddress": "10.0.0.4"
                },
                {
                    "NodeRole": "COMPUTE-3",
                    "PrivateIPAddress": "10.0.0.5"
                }
            ],
[...]
```

**Comment by 0xdabbad00** [comment]
Thank you for reporting this in. I'll fix this weekend.
