### ISSUE TITLE
error in find_admins

### ISSUE THREAD

**Issue by schosterbarak** [duo-labs/cloudmapper#465]
when running
python cloudmapper.py find_admins --account
 getting the following error:
`
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/Users/barak/Documents/dev/cloudmapper/commands/find_admins.py", line 9, in run
    admins = find_admins(accounts, findings=set())
  File "/Users/barak/Documents/dev/cloudmapper/shared/iam_audit.py", line 154, in find_admins
    admins.extend(find_admins_in_account(region, findings))
  File "/Users/barak/Documents/dev/cloudmapper/shared/iam_audit.py", line 306, in find_admins_in_account
    if is_admin_policy(policy_doc, location):
  File "/Users/barak/Documents/dev/cloudmapper/shared/iam_audit.py", line 79, in is_admin_policy
    findings.add(
NameError: name 'findings' is not defined
`
for some IAM entities

**Comment by schosterbarak** [comment]
fixed on: https://github.com/duo-labs/cloudmapper/pull/466
