### ISSUE TITLE
Error generating Report

### ISSUE THREAD

**Issue by StewartPenTest** [duo-labs/cloudmapper#534]
When running the following command (after running the collector script) I get an error

Command `python cloudmapper.py report --account myaccount-name`

I get this error:
```
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/root/aws/cloudmapper/commands/report.py", line 459, in run
    args, accounts, config = parse_arguments(arguments, parser)
  File "/root/aws/cloudmapper/shared/common.py", line 233, in parse_arguments
    accounts.append(get_account(account_name, config, args.config))
  File "/root/aws/cloudmapper/shared/common.py", line 170, in get_account
    if account["name"] == account_name:
KeyError: 'name'
```
I have tried using both the AWS account number and the name I used in the JSON file, both without luck.  I have also rerun the collector script using both methods.  What am I doing wrong or is there an issue?

**Comment by StewartPenTest** [comment]
My bad - error on my part.
