### ISSUE TITLE
Cannot iterate over null (null)

### ISSUE THREAD

**Issue by winnettjohnston** [duo-labs/cloudmapper#541]
```(cloudmapper) bash-3.2$ python3.7 cloudmapper.py prepare --config config.NAME.json --account NAME
Building data for account NAME (XXXXXXXXXXX)
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/Users//cloudmapper/commands/prepare.py", line 819, in run
    prepare(account, config, outputfilter)
  File "/Users//cloudmapper/commands/prepare.py", line 660, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/Users//cloudmapper/commands/prepare.py", line 419, in build_data_structure
    for region_json in get_regions(account, outputfilter):
  File "/Users//cloudmapper/shared/common.py", line 161, in get_regions
    regions = pyjq.all(".Regions[]{}".format(region_filter), region_data)
  File "/Users//.local/share/virtualenvs/cloudmapper-gEVbp0T_/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)```

It works for a single account but fails on all 5 of my others with this same message. Too bad it would have been nice to have

**Comment by winnettjohnston** [comment]
My bad.

problem was i never executed the collect command after my first round

```python cloudmapper.py collect --account my_account```
