### ISSUE TITLE
Failure in prepare command while filtering by --vpc-ids

### ISSUE THREAD

**Issue by usherirl** [duo-labs/cloudmapper#575]
I have completed the collect and a normal prepare works fine but in order to make the output more workable i have been trying to filter by the --vpc-ids. I have gotten it to work by specifying --regions & --vpc-ids but mainly i get the error below. I have checked the collect files under account data and it has the information about the vpc id in question. The filter for vpc names fails also.

`Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/home/cloudmapper/commands/prepare.py", line 819, in run
    prepare(account, config, outputfilter)
  File "/home/cloudmapper/commands/prepare.py", line 660, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/home/cloudmapper/commands/prepare.py", line 477, in build_data_structure
    add_node_to_subnets(region, node, nodes)
  File "/home/cloudmapper/commands/prepare.py", line 329, in add_node_to_subnets
    if len(node.subnets) == 0 and vpc.local_id == node._parent.local_id:`

**Comment by jmyork** [comment]
I am getting the exact same error.  It all goes back to a AttributeError: 'NoneType' object has no attribute 'local_id' for me.
