### ISSUE TITLE
collect_data.sh doesn't like Ubuntu on Windows 10 subsystem

### ISSUE THREAD

**Issue by asloan7** [duo-labs/cloudmapper#58]
Dies very quickly:
cloudmapper$ ./collect_data.sh --account 2267e1
* Startup checks
jq - commandline JSON processor [version 1.3]
Usage: jq [options] <jq filter> [file...]

**Comment by 0xdabbad00** [comment]
You could try using the `gather` command of CloudMapper instead of the script `collect_data.sh`.  They do the same thing.  You'd run `python cloudmapper.py gather --account-name 2267e1`

With further info about the error, I can't debug this further.  Does the script just die without any error messages?

**Comment by asloan7** [comment]
Yes, gather works, I just thought I'd log this issue.
Maybe it is the jq version? jq --version
jq version 1.3

set -x at the top of collect_data.sh: 
...
+ aws --version
+ '[' 0 -ne 0 ']'
+ aws --output json sts get-caller-identity
+ '[' 0 -ne 0 ']'
+ jq --help
jq - commandline JSON processor [version 1.3]
Usage: jq [options] <jq filter> [file...]

**Comment by 0xdabbad00** [comment]
I run jq version 1.5, but I can't tell what the issue would be in this case.

**Comment by jeremych1000** [comment]
Running `python cloudmapper.py collect --account-name dev1` on WSL gives me this as well. I think it's trying to write a file with a colon in the filename, which isn't permitted by Windows?

```
Traceback (most recent call last):
  File "cloudmapper.py", line 68, in <module>
    main()
  File "cloudmapper.py", line 63, in main
    commands[command].run(arguments)
  File "/mnt/c/Users/jeremych/Documents/GitHub/cloudmapper/commands/collect.py", line 198, in run
    collect(args)
  File "/mnt/c/Users/jeremych/Documents/GitHub/cloudmapper/commands/collect.py", line 171, in collect
    call_function(outputfile, handler, method_to_call, parameters)
  File "/mnt/c/Users/jeremych/Documents/GitHub/cloudmapper/commands/collect.py", line 83, in call_function
    with open(outputfile, 'w+') as f:
IOError: [Errno 22] invalid mode ('w+') or filename: 'account-data/./dev1/ap-northeast-1/rds-describe-db-snapshot-attributes/rds:amt24112017-2018-06-11-13-36'
```

**Comment by 0xdabbad00** [comment]
For this issue @jeremych1000, I think you're correct about disliking colons.  I have some code to sanitize the parameters in https://github.com/duo-labs/cloudmapper/blob/dff569c94a1f1f64f291b5fa6d5eca4c85e40c47/commands/collect.py#L31 but I should expand that to account for colons.

**Comment by jeremych1000** [comment]
From [MSDN](https://msdn.microsoft.com/en-us/library/aa365247),
```
The following reserved characters:

< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

**Comment by 0xdabbad00** [comment]
Special characters are currently handled here: https://github.com/duo-labs/cloudmapper/blob/3249aacb2d701847a5360e2d56f7243f44c909be/commands/collect.py#L31

This doesn't handle all special characters, and worse causes some code paths to fail because it expects a filename that doesn't exist because the characters were changed.  To fix this, all filenames that are based on parameters need to be encoded and decoded with `base64.urlsafe_b64encode(your_string)`
