### ISSUE TITLE
Error running report

### ISSUE THREAD

**Issue by alex4poshmark** [duo-labs/cloudmapper#615]
"collect" ran successfully but report fails:

python cloudmapper.py report --account myaccount
* Getting resource counts
  - myaccount
* Getting IAM data
  - myaccount
* Getting public resource data
  - myaccount
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/cloudmapper/commands/report.py", line 471, in run
    report(accounts, config, args)
  File "/cloudmapper/commands/report.py", line 263, in report
    public_nodes, _ = get_public_nodes(account, config, use_cache=True)
  File "/cloudmapper/shared/public.py", line 89, in get_public_nodes
    network = build_data_structure(account, config, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 445, in build_data_structure
    nodes = get_resource_nodes(region, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 395, in get_resource_nodes
    node = Redshift(region, node_json)
  File "/cloudmapper/shared/nodes.py", line 812, in __init__
    if vpc.local_id == json_blob["VpcId"]:
KeyError: 'VpcId'

**Comment by alex4poshmark** [comment]
It appears issue is that Redshift cluster is not created in VPC so there is no VpcId associated. But it looks like VpcId is required in other places. Do you plan to address this or non-VPC Redshift should be skipped?

**Comment by 0xdabbad00** [comment]
This should be fixed, but I won't have time to get to this until February, 2020.

**Comment by alexdaviestray** [comment]
If you don't mind removing Redshift from the results, one workaround is to comment out the redshift code In commands/prepare.py:

# Redshift clusters
#for node_json in get_redshift(region):
#    node = Redshift(region, node_json)
#    nodes[node.arn] = node

**Comment by Gyja** [comment]
> If you don't mind removing Redshift from the results, one workaround is to comment out the redshift code In commands/prepare.py:
> 
> # Redshift clusters
> #for node_json in get_redshift(region):
> # node = Redshift(region, node_json)
> # nodes[node.arn] = node

-------------------

Without the change to prepare.py - You get the following error:
python cloudmapper.py report --account fws
* Getting resource counts
  - fws
* Getting IAM data
  - fws
* Getting public resource data
  - fws
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/cloudmapper/commands/report.py", line 471, in run
    report(accounts, config, args)
  File "/cloudmapper/commands/report.py", line 263, in report
    public_nodes, _ = get_public_nodes(account, config, use_cache=True)
  File "/cloudmapper/shared/public.py", line 89, in get_public_nodes
    network = build_data_structure(account, config, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 477, in build_data_structure
    add_node_to_subnets(region, node, nodes)
  File "/cloudmapper/commands/prepare.py", line 329, in add_node_to_subnets
    if len(node.subnets) == 0 and node._parent and vpc.local_id == node._parent.local_id:
  File "/cloudmapper/shared/nodes.py", line 497, in subnets
    return pyjq.all(
  File "/cloudmapper/venv/lib/python3.8/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)

With the change to prepare.py 
    # Redshift clusters
    #for node_json in get_redshift(region):
    #    node = Redshift(region, node_json)
    #   nodes[node.arn] = node

The error is:
ython cloudmapper.py prepare --account fws
Building data for account fws (12...deleted to protect the innocent)
- 0 nodes built in region eu-north-1
- 0 nodes built in region ap-south-1
- 0 nodes built in region eu-west-3
- 0 nodes built in region eu-west-2
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/cloudmapper/commands/prepare.py", line 831, in run
    prepare(account, config, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 660, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 477, in build_data_structure
    add_node_to_subnets(region, node, nodes)
  File "/cloudmapper/commands/prepare.py", line 329, in add_node_to_subnets
    if len(node.subnets) == 0 and node._parent and vpc.local_id == node._parent.local_id:
  File "/cloudmapper/shared/nodes.py", line 497, in subnets
    return pyjq.all(
  File "/cloudmapper/venv/lib/python3.8/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)
