### ISSUE TITLE
find_admins KeyError

### ISSUE THREAD

**Issue by maestretti** [duo-labs/cloudmapper#618]
```
(cloudmapper) root@f9efb2165ca6:/opt/cloudmapper# python cloudmapper.py find_admins --account YOUR_ACCOUNT
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/opt/cloudmapper/commands/find_admins.py", line 31, in run
    admins = find_admins(accounts, args, findings=set())
  File "/opt/cloudmapper/shared/iam_audit.py", line 147, in find_admins
    region, findings, privs_to_look_for, include_restricted
  File "/opt/cloudmapper/shared/iam_audit.py", line 276, in find_admins_in_account
    policy["Arn"],
KeyError: 'Arn'
```

**Comment by 0xdabbad00** [comment]
Looks like I need to change `policy` to `policy_doc` at https://github.com/duo-labs/cloudmapper/blob/1e60e1fb0bf5ad71d8514c2f5a3a2696b130f4cc/shared/iam_audit.py#L276

**Comment by w0rmr1d3r** [comment]
That line has changed to `role["Arn"]`, does this issue make any sense now?
@0xdabbad00 @maestretti
