### ISSUE TITLE
prepare.py iterates over None

### ISSUE THREAD

**Issue by Cerebus** [duo-labs/cloudmapper#625]
When running `prepare` with vpc filtering (--vpc-ids and --vpc-names), it errors:

```
❯ python cloudmapper.py prepare --account xxxx --vpc-ids vpc-xxxxxxxx
Building data for account xxxx (1234567890)
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/Users/tmiller/Documents/projects/levelup/cloudmapper/commands/prepare.py", line 819, in run
    prepare(account, config, outputfilter)
  File "/Users/tmiller/Documents/projects/levelup/cloudmapper/commands/prepare.py", line 660, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/Users/tmiller/Documents/projects/levelup/cloudmapper/commands/prepare.py", line 477, in build_data_structure
    add_node_to_subnets(region, node, nodes)
  File "/Users/tmiller/Documents/projects/levelup/cloudmapper/commands/prepare.py", line 329, in add_node_to_subnets
    if len(node.subnets) == 0 and vpc.local_id == node._parent.local_id:
AttributeError: 'NoneType' object has no attribute 'local_id'
```

This happens because `node._parent` is None.  A fix for this condition is easy, but I don't know if it's normal or something wrong with the collection.  I'm running in partition `aws-us-gov` and had to fix collection.

**Comment by 0xdabbad00** [comment]
Can you debug this further?  For example printing out what type of `node` is being looked at? That might give some clues.

**Comment by Cerebus** [comment]
Looks like it's only VpcEndpoints:
```
[...]
<shared.nodes.Elbv2 object at 0x1074bbb50>
<shared.nodes.Elbv2 object at 0x1074bbbd0>
<shared.nodes.Elbv2 object at 0x1074bb690>
<shared.nodes.Elbv2 object at 0x1074bb750>
<shared.nodes.VpcEndpoint object at 0x106c171d0>
^ NO PARENT
<shared.nodes.VpcEndpoint object at 0x106c17150>
<shared.nodes.VpcEndpoint object at 0x106c170d0>
^ NO PARENT
<shared.nodes.VpcEndpoint object at 0x106c17250>
^ NO PARENT
<shared.nodes.Lambda object at 0x1074bbd50>
<shared.nodes.Lambda object at 0x1074bbd10>
[...]
```

**Comment by Cerebus** [comment]
Yep, that's exactly what's happening.  The filter seems to allow through VPN endpoints from other VPCs.

**Comment by Cerebus** [comment]
I think this means anything without `_parent` can be safely skipped, since it should be dropped anyway.  That's a one-line change.  If that seems right to you, let me know and I'll send a PR.
