### ISSUE TITLE
SAML Prodvider / AzureAD

### ISSUE THREAD

**Issue by Gomory666** [duo-labs/cloudmapper#645]
Hello,

Firstly, thanks for this app! :) 

So, I have a problem with cloudmapper and saml of AzureAD : 

user1:~/cloudmapper/cloudmapper# python3 cloudmapper.py weboftrust --account all --config prod/config.json
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/root/cloudmapper/cloudmapper/commands/weboftrust.py", line 473, in run
    cytoscape_json = weboftrust(args, accounts, config)
  File "/root/cloudmapper/cloudmapper/commands/weboftrust.py", line 356, in weboftrust
    get_nodes_and_connections(account, nodes, connections, args)
  File "/root/cloudmapper/cloudmapper/commands/weboftrust.py", line 337, in get_nodes_and_connections
    get_iam_trusts(account, nodes, connections, connections_to_get)
  File "/root/cloudmapper/cloudmapper/commands/weboftrust.py", line 215, in get_iam_trusts
    "Unknown federation provider: {}".format(principal["Federated"])
Exception: Unknown federation provider: arn:aws:iam::xxxxxxxxxxx:saml-provider/AzureAD

It's just with cloudmapper weboftrust*

Thanks for you help

**Comment by 0xdabbad00** [comment]
cc @nimrodkor for visibility as this relates to #643.

@Gomory666 You'll need to add AzureAD as another federation provider somewhere around https://github.com/duo-labs/cloudmapper/blob/c2058ae5cda0ebe90114f0387a734ec96f063316/commands/weboftrust.py#L228
