### ISSUE TITLE
ImportError: No module named parliament

### ISSUE THREAD

**Issue by LeeJCherry** [duo-labs/cloudmapper#655]
Cloned repo - installed all pre-reqs (Windows Subsystem for Linux)

Tried to run the demo, get the following

`~/w/t/cloudmapper> python cloudmapper.py prepare --config config.json.demo --account demo                                                                                                                                            08:07:14
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 55, in main
    module = importlib.import_module(full_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/lee/work/tools/cloudmapper/commands/access_check.py", line 13, in <module>
    import parliament
ImportError: No module named parliament`

**Comment by 0xdabbad00** [comment]
Did you install this from pipenv?  parliament should have been installed via https://github.com/duo-labs/cloudmapper/blob/8a31873c5222d15d353761c55b6f82e0d8f0022b/Pipfile#L18 

Looks like I've missed the Docker imports though:
- https://github.com/duo-labs/cloudmapper/blob/8a31873c5222d15d353761c55b6f82e0d8f0022b/Dockerfile#L11
- https://github.com/duo-labs/cloudmapper/blob/8a31873c5222d15d353761c55b6f82e0d8f0022b/auditor/resources/Dockerfile#L10

**Comment by LeeJCherry** [comment]
I did install via the pre-reqs from the readme.  

It' working now, I think it must have been the clash of pythin versions, I needed to switch Python to Python3.  Pretty new to Python / Linux.

**Comment by 0xdabbad00** [comment]
I've ticketed the docker issues at #656 as those aren't relevant to you.  I'm guessing you may have missed instructions to use the `pipenv`, but the docs could use with some better organization and clearer guidance if you have any thoughts. I'm going to close this out as it sounds like your problem is solved.

**Comment by AwolDes** [comment]
Just thought I would add that this error also seems to be raised when credentials are not supplied. This is the output from my terminal (Ubuntu 18.04)

```bash
[austin:~/cloudmapper] [cloudmapper-4pVfqMgC] master ± python cloudmapper.py prepare --config config.demo.json
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 55, in main
    module = importlib.import_module(full_package_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/austin/cloudmapper/commands/access_check.py", line 13, in <module>
    import parliament
ModuleNotFoundError: No module named 'parliament'

[austin:~/cloudmapper] [cloudmapper-4pVfqMgC] master ± aws-vault exec sandbox-admin -- python cloudmapper.py prepare --config config.json
Building data for account demo (123456789)
- 16 nodes built in region us-east-1
- 3 external CIDRs built
- 35 connections built
```

**Comment by 0xdabbad00** [comment]
That should not be the case. The `prepare` command does not make any AWS calls (so aws-vault is not needed), and aws-vault should not be changing what libraries you have available. I think something else is happening in your situation @AwolDes

**Comment by jiacheng-0** [comment]
Is this workable on Windows WSL?
