### ISSUE TITLE
Error fetching data with more then 8 AWS account in CloudmapperauditStack

### ISSUE THREAD

**Issue by acidflash** [duo-labs/cloudmapper#687]
When i run `aws events put-events --entries '[{"Source":"cloudmapper","DetailType":"start","Detail":"{}"}]'` om CloudmapperauditStack with more then 8 accounts in the `config` and `config.json` i get error:

`Completed 3.1 KiB/3.1 KiB (59.0 KiB/s) with 1 file(s) remaining download: s3://XXXXXX/run_cloudmapper.sh to ./run_cloudmapper.sh

Runnning run_cloudmapper

Completed 2.3 KiB/2.3 KiB (73.2 KiB/s) with 1 file(s) remaining download: s3://XXXXXX/config to ../../root/.aws/config

Completed 1.3 KiB/1.3 KiB (31.6 KiB/s) with 1 file(s) remaining download: s3://XXXXXX/config.json to ./config.json

Completed 334 Bytes/334 Bytes (2.9 KiB/s) with 1 file(s) remaining download: s3://XXXXXX/audit_config_override.yaml to config/audit_config_override.yaml

children pids = 54

children pids = 54 55

children pids = 54 55 56

*** Collecting from XXXXXX

children pids = 54 55 56 57

children pids = 54 55 56 57 59

*** Collecting from XXXXXX

children pids = 54 55 56 57 59 60

children pids = 54 55 56 57 59 60 62

*** Collecting from XXXXXX

children pids = 54 55 56 57 59 60 62 63

children pids = 54 55 56 57 59 60 62 63 65

*** Collecting from XXXXXX

children pids = 54 55 56 57 59 60 62 63 65 66

children pids = 54 55 56 57 59 60 62 63 65 66 68

*** Collecting from XXXXXX

children pids = 54 55 56 57 59 60 62 63 65 66 68 69

children pids = 54 55 56 57 59 60 62 63 65 66 68 69 71

*** Collecting from XXXXXX

children pids = 54 55 56 57 59 60 62 63 65 66 68 69 71 72

children pids = 54 55 56 57 59 60 62 63 65 66 68 69 71 72 74

*** Collecting from XXXXXX

*** Collecting from XXXXXX

children pids = 54 55 56 57 59 60 62 63 65 66 68 69 71 72 74 75

children pids = 54 55 56 57 59 60 62 63 65 66 68 69 71 72 74 75 77

*** Collecting from XXXXXX

*** Collecting from XXXXXX

*** Collecting from XXXXXX

*** Collecting from XXXXXX

*** Collecting from XXXXXX

*** Collecting from XXXXXX

*** Collecting from XXXXXX

*** Collecting from XXXXXX

*** Collecting from XXXXXX

ERROR: The collect command had an error for account XXXXXX

./run_cloudmapper.sh: line 25: 58 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

./run_cloudmapper.sh: line 25: 86 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

ERROR: The collect command had an error for account XXXXXX

ERROR: The collect command had an error for account XXXXXX

./run_cloudmapper.sh: line 25: 81 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

Traceback (most recent call last):

File "cloudmapper.py", line 72, in <module>

main()

File "cloudmapper.py", line 66, in main

commands[command].run(arguments)

File "/opt/cloudmapper/commands/collect.py", line 536, in run

self._loader = self._session.get_component('data_loader')

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/session.py", line 682, in get_component

return self._components.get_component(name)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/session.py", line 919, in get_component

self._components[name] = factory()

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/session.py", line 155, in <lambda>

lambda: create_loader(self.get_config_variable('data_path')))

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/session.py", line 238, in get_config_variable

logical_name)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/configprovider.py", line 293, in get_config_variable

return provider.provide()

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/configprovider.py", line 390, in provide

value = provider.provide()

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/configprovider.py", line 451, in provide

scoped_config = self._session.get_scoped_config()

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/session.py", line 337, in get_scoped_config

raise ProfileNotFound(profile=profile_name)

botocore.exceptions.ProfileNotFound: The config profile (XXXXXX) could not be found

Traceback (most recent call last):

File "cloudmapper.py", line 72, in <module>

main()

File "cloudmapper.py", line 66, in main

commands[command].run(arguments)

File "/opt/cloudmapper/commands/collect.py", line 536, in run

collect(args)

File "/opt/cloudmapper/commands/collect.py", line 248, in collect

iam = session.client("iam")

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/boto3/session.py", line 263, in client

aws_session_token=aws_session_token, config=config)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/session.py", line 835, in create_client

client_config=config, api_version=api_version)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/client.py", line 78, in create_client

service_model = self._load_service_model(service_name, api_version)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/client.py", line 116, in _load_service_model

api_version=api_version)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper

data = func(self, *args, **kwargs)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/loaders.py", line 383, in load_service_model

model = self.load_data(full_path)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper

data = func(self, *args, **kwargs)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/loaders.py", line 420, in load_data

found = self.file_loader.load_file(possible_path)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/botocore/loaders.py", line 173, in load_file

payload = fp.read().decode('utf-8')

OSError: [Errno 14] Bad address

./run_cloudmapper.sh: line 25: 82 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

ERROR: The collect command had an error for account XXXXXX

ERROR: The collect command had an error for account XXXXXX

./run_cloudmapper.sh: line 25: 61 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

ERROR: The collect command had an error for account XXXXXX

./run_cloudmapper.sh: line 25: 88 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

ERROR: The collect command had an error for account XXXXXX

ERROR: The collect command had an error for account XXXXXX

ERROR: The collect command had an error for account XXXXXX

./run_cloudmapper.sh: line 25: 78 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

./run_cloudmapper.sh: line 25: 76 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

ERROR: The collect command had an error for account XXXXXX  

Traceback (most recent call last):

File "/usr/bin/aws", line 27, in <module>

sys.exit(main())

File "/usr/bin/aws", line 23, in main

return awscli.clidriver.main()

File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 58, in main

driver = create_clidriver()

File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 67, in create_clidriver

load_plugins(session.full_config.get('plugins', {}),

File "/usr/lib/python3/dist-packages/botocore/session.py", line 351, in full_config

self._config = botocore.configloader.load_config(config_file)

File "/usr/lib/python3/dist-packages/botocore/configloader.py", line 

parsed = raw_config_parse(config_filename)

File "/usr/lib/python3/dist-packages/botocore/configloader.py", line 158, in raw_config_parse

if parse_subsections and config_value.startswith('\n'):

AttributeError: 'list' object has no attribute 'startswith'

./run_cloudmapper.sh: line 25: 70 Killed python cloudmapper.py collect --profile $1 --account $1 > collect_logs/$1

ERROR: The collect command had an error for account XXXXXX

Collection from XXXXXX was successful

ERROR: The collect command had an error for account XXXXXX

ERROR: The collect command had an error for account XXXXXX

Done waiting, start audit

Traceback (most recent call last):

File "cloudmapper.py", line 72, in <module>

main()

File "cloudmapper.py", line 66, in main

commands[command].run(arguments)

File "/opt/cloudmapper/commands/audit.py", line 75, in run

audit_command(accounts, config, args)

File "/opt/cloudmapper/commands/audit.py", line 14, in audit_command

findings = audit(accounts)

File "/opt/cloudmapper/shared/audit.py", line 

for region_json in get_regions(account):

File "/opt/cloudmapper/shared/common.py", line 161, in get_regions

regions = pyjq.all(".Regions[]{}".format(region_filter), region_data)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/pyjq.py", line 49, in all

return compile(script, vars, library_paths).all(_get_value(value, url, opener))

File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)

_pyjq.ScriptRuntimeError: Cannot iterate over null (null)

Generate the report

Traceback (most recent call last):

File "cloudmapper.py", line 72, in <module>

main()

File "cloudmapper.py", line 66, in main

commands[command].run(arguments)

File "/opt/cloudmapper/commands/report.py", line 471, in run

report(accounts, config, args)

File "/opt/cloudmapper/commands/report.py", line 91, in report

"collection_date": get_collection_date(account)[:

File "/opt/cloudmapper/shared/common.py", line 331, in get_collection_date

account_struct, "iam-get-credential-report", get_us_east_1(account_struct)

File "/opt/cloudmapper/shared/common.py", line 305, in get_us_east_1

for region_json in get_regions(account):

File "/opt/cloudmapper/shared/common.py", line 161, in get_regions

regions = pyjq.all(".Regions[]{}".format(region_filter), region_data)

File "/root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/lib/python3.7/site-packages/pyjq.py", line 49, in all

return compile(script, vars, library_paths).all(_get_value(value, url, opener))

File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)

_pyjq.ScriptRuntimeError: Cannot iterate over null (null)

ERROR: The report command had an error`

**Comment by 0xdabbad00** [comment]
I'm guessing the collection timed out, or possibly ran out of memory.  You can change the memory used here: https://github.com/duo-labs/cloudmapper/blob/master/auditor/lib/cloudmapperauditor-stack.js#L61

And timeout here: https://github.com/duo-labs/cloudmapper/blob/master/auditor/resources/entrypoint.sh#L11

**Comment by acidflash** [comment]
I tried to expand the memory before writing here, but only get.

`
CloudmapperauditorStack: creating CloudFormation changeset...
 0/5 | 6:45:31 AM | UPDATE_IN_PROGRESS   | AWS::ECS::TaskDefinition              | taskDefinition (taskDefinitionD5BB2FFF) Requested update requires the creation of a new physical resource; hence creating one.
 1/5 | 6:45:31 AM | UPDATE_FAILED        | AWS::ECS::TaskDefinition              | taskDefinition (taskDefinitionD5BB2FFF) The 'memory' setting for container 'cloudmapper-container' is greater than for the task. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 1ebbd889-fad5-4fe2-a0ac-499c530d7628)
	new TaskDefinition (/cloudmapper/auditor/node_modules/@aws-cdk/aws-ecs/lib/base/task-definition.ts:278:21)
	\_ new FargateTaskDefinition (/cloudmapper/auditor/node_modules/@aws-cdk/aws-ecs/lib/fargate/fargate-task-definition.ts:78:5)
	\_ new CloudmapperauditorStack (/cloudmapper/auditor/lib/cloudmapperauditor-stack.js:57:28)
	\_ Object.<anonymous> (/cloudmapper/auditor/bin/cloudmapperauditor.js:9:1)
	\_ Module._compile (internal/modules/cjs/loader.js:1147:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
	\_ Module.load (internal/modules/cjs/loader.js:996:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:896:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
	\_ internal/main/run_main_module.js:17:47
 1/5 | 6:45:32 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack            | CloudmapperauditorStack The following resource(s) failed to update: [taskDefinitionD5BB2FFF]. 
 2/5 | 6:45:40 AM | UPDATE_COMPLETE      | AWS::ECS::TaskDefinition              | taskDefinition (taskDefinitionD5BB2FFF) 

 ❌  CloudmapperauditorStack failed: Error: The stack named CloudmapperauditorStack is in a failed state: UPDATE_ROLLBACK_COMPLETE
    at /usr/local/Cellar/aws-cdk/1.28.0/libexec/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:165:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/usr/local/Cellar/aws-cdk/1.28.0/libexec/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:76:20)
    at Object.deployStack (/usr/local/Cellar/aws-cdk/1.28.0/libexec/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:156:7)
    at CdkToolkit.deploy (/usr/local/Cellar/aws-cdk/1.28.0/libexec/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:152:24)
    at main (/usr/local/Cellar/aws-cdk/1.28.0/libexec/lib/node_modules/aws-cdk/bin/cdk.ts:226:16)
    at initCommandLine (/usr/local/Cellar/aws-cdk/1.28.0/libexec/lib/node_modules/aws-cdk/bin/cdk.ts:169:9)
The stack named CloudmapperauditorStack is in a failed state: UPDATE_ROLLBACK_COMPLETE
`


And I don't think it depends on how long it takes, because the work only takes 16 minutes from start to finish.

**Comment by 0xdabbad00** [comment]
The first error was an error with CloudMapper running (python errors). This error is an error with the CDK deploying.

**Comment by acidflash** [comment]
So the answer is, that you can't run CloudMapper with more then ~8 accounts and you cant expand the memory in https://github.com/duo-labs/cloudmapper/blob/master/auditor/lib/cloudmapperauditor-stack.js#L61 do to CDP error?

**Comment by 0xdabbad00** [comment]
No and no. There is no limitation on the number of accounts that CloudMapper can scan. Your python error contains `botocore.exceptions.ProfileNotFound: The config profile (XXXXXX) could not be found` so it could just be that you didn't configure an account correctly.  You're going to have to debug that issue on your own.

And the amount of memory can be expanded. Again, you're going to have to debug that issue further on your own.
