### ISSUE TITLE
us-east-1 is hardcoded

### ISSUE THREAD

**Issue by deepti-nucleusteq** [duo-labs/cloudmapper#760]
Please mention the following:
- What command was run?
   python cloudmapper.py report 
- Are you working out of a virtualenv environment, Docker, or something else?
  venv

It could not collect any data for my account existing in region us-west-1.

- 0 nodes built in region us-west-1
account-data/nucleusteq/us-west-1/ec2-describe-vpc-peering-connections.json
- 0 external CIDRs built
- 0 connections built

It's not mentioned anywhere to create describe-regions.json.
I created it and added us-west-1 as it is the default region for my account.
I found :
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/Users/deeptibaghel/git/cloudmapper/commands/report.py", line 471, in run
    report(accounts, config, args)
  File "/Users/deeptibaghel/git/cloudmapper/commands/report.py", line 91, in report
    "collection_date": get_collection_date(account)[:10],
  File "/Users/deeptibaghel/git/cloudmapper/shared/common.py", line 330, in get_collection_date
    account_struct, "iam-get-credential-report", get_us_east_1(account_struct)
  File "/Users/deeptibaghel/git/cloudmapper/shared/common.py", line 309, in get_us_east_1
    raise Exception("us-east-1 not found")
Exception: us-east-1 not found

When I checked the code I found us_east_1 is hardcoded at multiple places. Does it work for us-east-1 region only ?

**Comment by 0xdabbad00** [comment]
You need to run `collect`.
