### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by pmajkutewicz** [duo-labs/cloudmapper#779]
I've configure aws-vault , after that:

    python3 -m venv ./venv && source venv/bin/activate
    pip install -r requirements.txt
    python cloudmapper.py collect --account xxx

And as output I'm getting:
```AWSServiceRoleForAmazonCognitoIdpEmailService
  Response already collected at account-data/./xxx/us-east-1/iam-generate-service-last-accessed-details/arn%3Aaws%3Aiam%3A%3A291233021721%3Arole%2Faws-service-role%2Fops.apigateway.amazonaws.com%2FAWSServiceRoleForAPIGateway
  Making call for account-data/./xxx/us-east-1/iam-generate-service-last-accessed-details/arn%3Aaws%3Aiam%3A%3A291233021721%3Arole%2Faws-service-role%2Fecs.application-autoscaling.amazonaws.com%2FAWSServiceRoleForApplicationAutoScaling_ECSService
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File ".../cloudmapper/commands/collect.py", line 601, in run
    collect(args)
  File ".../cloudmapper/commands/collect.py", line 503, in collect
    call_function(
  File ".../cloudmapper/commands/collect.py", line 192, in call_function
    with open(outputfile, "w+") as f:
OSError: [Errno 36] File name too long: 'account-data/./xxx/us-east-1/iam-generate-service-last-accessed-details/arn%3Aaws%3Aiam%3A%3A291233021721%3Arole%2Faws-service-role%2Fecs.application-autoscaling.amazonaws.com%2FAWSServiceRoleForApplicationAutoScaling_ECSService'

Python version:
    Python 3.8.5

**Comment by pmajkutewicz** [comment]
Moved to other directory `/tmp` and it is working.
