### ISSUE TITLE
Bug in prepare `takes exactly 3 arguments (2 given)`

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#8]
I received a bug report on Slack https://awssecurityforum.slack.com/files/U7K04K073/F9BNUTJ03/-.txt

```
Traceback (most recent call last):
  File "cloudmapper.py", line 121, in <module>
    main()
  File "cloudmapper.py", line 111, in main
    run_prepare(arguments)
  File "cloudmapper.py", line 90, in run_prepare
    prepare(account, config, outputfilter)
  File ".../Scrap/cloudmapper/cloudmapper/prepare.py", line 339, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File ".../cloudmapper/cloudmapper/prepare.py", line 300, in build_data_structure
    for c, reasons in get_connections(cidrs, vpc, outputfilter).iteritems():
  File ".../cloudmapper/cloudmapper/prepare.py", line 199, in get_connections
    add_connection(connections, source, target, sg)
  File ".../cloudmapper/cloudmapper/prepare.py", line 129, in add_connection
    reasons = connections.get(Connection(source, target), [])
TypeError: __eq__() takes exactly 3 arguments (2 given)%
```

**Comment by laurrentt** [comment]
Just got the same error. I'll comment the issue if I find something.

**Comment by laurrentt** [comment]
I've made a PR that seems to fix the issue https://github.com/duo-labs/cloudmapper/pull/9.

**Comment by ccao93** [comment]
I also got this exact same issue.

**Comment by 0xdabbad00** [comment]
Should be resolved now with the merged PR, thank you @laurrentt !
