### ISSUE TITLE
Failed on Run 

### ISSUE THREAD

**Issue by ghost** [duo-labs/cloudmapper#936]
python3 cloudmapper.py                               
Traceback (most recent call last):
  File "/root/cloudmapper/cloudmapper.py", line 72, in <module>
    main()
  File "/root/cloudmapper/cloudmapper.py", line 55, in main
    module = importlib.import_module(full_package_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/cloudmapper/commands/amis.py", line 5, in <module>
    import pyjq
ModuleNotFoundError: No module named 'pyjq'

**Comment by ShahidAkhterSec** [comment]
I am using it on latest kali linux Version

**Comment by lcassiol** [comment]
same here
