### ISSUE TITLE
Region Data Not found

### ISSUE THREAD

**Issue by veritasecops** [duo-labs/cloudmapper#940]
How do I fix this?

`WARNING: This functionality is no longer maintained
WARNING: This functionality is no longer maintained
Building data for account RadarApp (765843959562)
Traceback (most recent call last):
  File "/home/user/repos/cloudmapper/cloudmapper.py", line 72, in <module>
    main()
  File "/home/user/repos/cloudmapper/cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/home/user/repos/cloudmapper/commands/prepare.py", line 842, in run
    prepare(account, config, outputfilter)
  File "/home/user/repos/cloudmapper/commands/prepare.py", line 669, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/home/user/repos/cloudmapper/commands/prepare.py", line 424, in build_data_structure
    for region_json in get_regions(account, outputfilter):
  File "/home/user/repos/cloudmapper/shared/common.py", line 159, in get_regions
    raise InvalidAccountData("region data not found for {}".format(account.name))
shared.common.InvalidAccountData: region data not found for RadarApp`

**Comment by DilLip-Chowdary-Codes** [comment]
Getting the same, any fix?

**Comment by masch8855** [comment]
Make sure you have the demo data in account-data path.

**Comment by ishtylerc** [comment]
Any update on this?

**Comment by confusedcrib** [comment]
I received this error when trying to run another command before `collect` because it's the first error that gets raised if there's nothing in the `account-data` folder

**Comment by erict35000** [comment]
Hi,

I was unable to install cloud mapper on macOS Monterey, Ubuntu 22.04 and Mint.

So I decided to install docker on macOS Monterey and follow these instructions : https://github.com/duo-labs/cloudmapper/issues/896

Everything is fine, but when I type python cloudmapper.py report --accounts XXX,XXX, what I have to input as accounts. I try with audit, my account on AWS and the number of AWSaccount. I use a specific config.json for my AWS platform but it asks a region or tells me audit our xxxx are not in my config file.

Could you please tell me what I need to add to my config.json file ?


Regards
Eric
