### ISSUE TITLE
This error originates from a subprocess, and is likely not a problem with pip.   ERROR: Failed building wheel for pyjq

### ISSUE THREAD

**Issue by suprajasutti** [duo-labs/cloudmapper#960]
Please mention the following:
- What command was run? pip install -r requirements.txt
- Are you working out of a virtualenv environment, Docker, or something else?virtualenv
While running this command, I am getting failed building wheel for pyjq
![image](https://github.com/duo-labs/cloudmapper/assets/129878000/9ab870f4-5392-4212-8fb0-fdd62071fdaf)

**Comment by mckirk** [comment]
For me, this problem occurred because my Python 3.12.3 on Ubuntu 24.04 didn't have lib2to3 installed anymore. I fixed it with `sudo apt install python3-lib2to3`.

**Comment by CapyBarr1** [comment]
same issue here

**Comment by blacklistAPT** [comment]
Hi @suprajasutti, I've resolved this error by following these steps:

1. Install necessary packages:
`sudo apt-get install autoconf automake libtool`
2. Install pyjq
`pip3 install pyjq` - This installs pyjq version 2.6.0 without any issues.
3. Update requirements.txt:
Replace pyjq version with pyjq==2.6.0
4. Reinstall dependencies:
 `pip3 install -r requirements.txt `

Please ensure you execute these commands within the virtual environment created for cloudmapper.

Let me know if this fixes your error.

**Comment by theazz** [comment]
Same error on macos m3. 


  ```
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      <string>:34: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              By 2024-Nov-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************

      !!
      Traceback (most recent call last):
        File "/Users/az/Slmn/tmp/cloudmapper/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/az/Slmn/tmp/cloudmapper/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/az/Slmn/tmp/cloudmapper/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zz/1dl16zh96ds00ydgls8s08k80000gp/T/pip-build-env-q8gw5y53/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zz/1dl16zh96ds00ydgls8s08k80000gp/T/pip-build-env-q8gw5y53/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/zz/1dl16zh96ds00ydgls8s08k80000gp/T/pip-build-env-q8gw5y53/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/zz/1dl16zh96ds00ydgls8s08k80000gp/T/pip-build-env-q8gw5y53/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 54, in <module>
        File "/private/var/folders/zz/1dl16zh96ds00ydgls8s08k80000gp/T/pip-install-_57vroka/matplotlib_d174e27a7cc2409ba85bb712e92009cb/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/zz/1dl16zh96ds00ydgls8s08k80000gp/T/pip-install-_57vroka/matplotlib_d174e27a7cc2409ba85bb712e92009cb/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zz/1dl16zh96ds00ydgls8s08k80000gp/T/pip-install-_57vroka/matplotlib_d174e27a7cc2409ba85bb712e92009cb/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```


I followed the installation guide exactly as it was written on reame.md.

**Comment by jharnois4512** [comment]
Same error as above: 
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
